### ISSUE TITLE
Does not run in browser

### ISSUE THREAD

**Issue by OtterCodes101** [Lostguestsneeze/FalconCraft#3]
README.md has incorrect information, FalconCraft does not run in your browser, it runs on a cloud service.

**Comment by Lostguestsneeze** [comment]
OtterCodes101 Try Keeping The Offline Version On Before Going To An Offline Area If You Know How To Improve I Would Be Happy To Make You A Contributor

**Comment by Lostguestsneeze** [comment]
OtterCodes101 Try Keeping The Offline Version On Before Going To An Offline Area If You Know How To Improve I Would Be Happy To Make You A Contributor

**Comment by Lostguestsneeze** [comment]
OtterCodes101 Try Keeping The Offline Version On Before Going To An Offline Area If You Know How To Improve I Would Be Happy To Make You A Contributor

**Comment by Lostguestsneeze** [comment]
OtterCodes101 Try Keeping The Offline Version On Before Going To An Offline Area If You Know How To Improve I Would Be Happy To Make You A Contributor

**Comment by Lostguestsneeze** [comment]
OtterCodes101 Try Keeping The Offline Version On Before Going To An Offline Area If You Know How To Improve I Would Be Happy To Make You A Contributor

**Comment by Lostguestsneeze** [comment]
Also The Emulator Runs In The Browser So The README.md Is Fully Correct

**Comment by Lostguestsneeze** [comment]
Also Is This AN Actual Issue

**Comment by OtterCodes101** [comment]
you know how you can improve? probably make the emulator actually run client side

**Comment by OtterCodes101** [comment]
or, you could use [this](https://testsigma.com/online-android-emulator) instead of appetize, as it doesn't have a limit of time spent using falconcraft.
